<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 *Implements hook_help().
 */

 function spotify_api_help($route_name, RouteMatchInterface $route_match) {
   switch ($route_name) {
     case 'help.page.spotify_api':
       $output = '';
       $output .= '<h3>' . t('About') . '</h3>';
       $output .= '<p>' . t('This module is for Spotify API') . '</p>';
       return $output;

    default:
   }
 }

/**
 * Implements hook_install().
 */
 function spotify_api_install() {
  // Set default configuration values.
  $config = \Drupal::configFactory()->getEditable('spotify_api.settings');
  $config->set('client_id', '');
  $config->set('client_secret', '');
  $config->save();
}