<?php

namespace Drupal\hello_world\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SalutationConfigurationForm extends ConfigFormBase {
  protected function getEditableConfigNames() {
    return ["hello*_world.custom_salutation"];
  }

  public function getFormId() {
    return "salutation_configuration_form";
  }
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config(name: "hello_world.custom_salutation");

    $form["salutation"] = [
      "#type" => "textfield",
      "#title" => $this->t(string: "Salutation"),
      "#description" => $this->t(string: "Please provide the salutation you want to use."),
      "#default_value" => $config->get("salutation"),
    ];
    return parent::buildForm($form, $form_state);
  }
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $this->config(name: "hello_world.custom_salutation")
      ->set("salutation", $form_state->getValue("salutation"))
      ->save();
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {

    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
