<?php

/**
 * @file
 * Music Search module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function music_search_help($route_name, RouteMatchInterface $routeMatch) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a Spotify API') . '</p>';
      return $output;

    default;
  }
}
